BEGIN TRANSACTION;
DROP TABLE IF EXISTS `book_synonyms`;
CREATE TABLE IF EXISTS `book_synonyms` (
    `book_id`       TEXT NOT_NULL,
    `synonym`       TEXT NOT_NULL
    PRIMARY KEY(`book_id`)
);

INSERT INTO `book_synonyms` (book_id, synonym) VALUES
 ("genesis", "gen"),
 ("genesis", "ge"),
 ("genesis", "gn"),
 ("genesis", "genesis"),
 ("exodus", "exo"),
 ("exodus", "ex"),
 ("exodus", "exod"),
 ("exodus", "exodus"),
 ("leviticus", "lev"),
 ("leviticus", "le"),
 ("leviticus", "lv"),
 ("leviticus", "leviticus"),
 ("numbers", "num"),
 ("numbers", "nu"),
 ("numbers", "nm"),
 ("numbers", "nb"),
 ("numbers", "numbers"),
 ("deuteronomy", "deut"),
 ("deuteronomy", "dt"),
 ("deuteronomy", "deuteronomy"),
 ("joshua", "josh"),
 ("joshua", "jos"),
 ("joshua", "jo"),
 ("joshua", "joshua"),
 ("judges", "judg"),
 ("judges", "jdg"),
 ("judges", "jg"),
 ("judges", "jgs"),
 ("judges", "jdgs"),
 ("judges", "judges"),
 ("ruth", "rth"),
 ("ruth", "ru"),
 ("ruth", "ruth"),
 ("1samuel", "1 sam"),
 ("1samuel", "1 sa"),
 ("1samuel", "1samuel"),
 ("1samuel", "1s"),
 ("1samuel", "i sa"),
 ("1samuel", "1 sm"),
 ("1samuel", "1sa"),
 ("1samuel", "i sam"),
 ("1samuel", "1sam"),
 ("1samuel", "i samuel"),
 ("1samuel", "1st samuel"),
 ("1samuel", "first samuel"),
 ("1samuel", "1 samuel"),
 ("2samuel", "2 sam"),
 ("2samuel", "2 sa"),
 ("2samuel", "2s"),
 ("2samuel", "ii sa"),
 ("2samuel", "2 sm"),
 ("2samuel", "2sa"),
 ("2samuel", "ii sam"),
 ("2samuel", "2sam"),
 ("2samuel", "ii samuel"),
 ("2samuel", "2samuel"),
 ("2samuel", "2nd samuel"),
 ("2samuel", "second samuel"),
 ("2samuel", "2 samuel"),
 ("1kings", "1 kgs"),
 ("1kings", "1 ki"),
 ("1kings", "1k"),
 ("1kings", "i kgs"),
 ("1kings", "1kgs"),
 ("1kings", "i ki"),
 ("1kings", "1ki"),
 ("1kings", "i kings"),
 ("1kings", "1kings"),
 ("1kings", "1st kgs"),
 ("1kings", "1st kings"),
 ("1kings", "first kings"),
 ("1kings", "first kgs"),
 ("1kings", "1kin"),
 ("1kings", "1 kings"),
 ("2kings", "2 kgs"),
 ("2kings", "2 ki"),
 ("2kings", "2k"),
 ("2kings", "ii kgs"),
 ("2kings", "2kgs"),
 ("2kings", "ii ki"),
 ("2kings", "2ki"),
 ("2kings", "ii kings"),
 ("2kings", "2kings"),
 ("2kings", "2nd kgs"),
 ("2kings", "2nd kings"),
 ("2kings", "second kings"),
 ("2kings", "second kgs"),
 ("2kings", "2kin"),
 ("2kings", "2 kings"),
 ("1chronicles", "1 chron"),
 ("1chronicles", "1 ch"),
 ("1chronicles", "i ch"),
 ("1chronicles", "1ch"),
 ("1chronicles", "1 chr"),
 ("1chronicles", "i chr"),
 ("1chronicles", "1chr"),
 ("1chronicles", "i chron"),
 ("1chronicles", "1chron"),
 ("1chronicles", "i chronicles"),
 ("1chronicles", "1chronicles"),
 ("1chronicles", "1st chronicles"),
 ("1chronicles", "first chronicles"),
 ("1chronicles", "1 chronicles"),
 ("2chronicles", "2 chron"),
 ("2chronicles", "2 ch"),
 ("2chronicles", "ii ch"),
 ("2chronicles", "2ch"),
 ("2chronicles", "ii chr"),
 ("2chronicles", "2chr"),
 ("2chronicles", "ii chron"),
 ("2chronicles", "2chron"),
 ("2chronicles", "ii chronicles"),
 ("2chronicles", "2chronicles"),
 ("2chronicles", "2nd chronicles"),
 ("2chronicles", "second chronicles"),
 ("2chronicles", "2 chronicles"),
 ("ezra", "ezra"),
 ("ezra", "ezr"),
 ("nehemiah", "neh"),
 ("nehemiah", "ne"),
 ("nehemiah", "nehemiah"),
 ("esther", "esth"),
 ("esther", "es"),
 ("esther", "esther"),
 ("job", "jb"),
 ("job", "job"),
 ("psalm", "pslm"),
 ("psalm", "ps"),
 ("psalm", "psalms"),
 ("psalm", "psa"),
 ("psalm", "psm"),
 ("psalm", "pss"),
 ("psalm", "psalm"),
 ("proverbs", "prov"),
 ("proverbs", "pr"),
 ("proverbs", "prv"),
 ("proverbs", "proverbs"),
 ("ecclesiastes", "eccles"),
 ("ecclesiastes", "ec"),
 ("ecclesiastes", "eccl"),
 ("ecclesiastes", "ecc"),
 ("ecclesiastes", "qoh"),
 ("ecclesiastes", "qoheleth"),
 ("ecclesiastes", "ecclesiastes"),
 ("isaiah", "isa"),
 ("isaiah", "is"),
 ("isaiah", "isaiah"),
 ("jeremiah", "jer"),
 ("jeremiah", "je"),
 ("jeremiah", "jr"),
 ("jeremiah", "jeremiah"),
 ("lamentations", "lam"),
 ("lamentations", "la"),
 ("lamentations", "lamentations"),
 ("ezekiel", "ezek"),
 ("ezekiel", "eze"),
 ("ezekiel", "ezk"),
 ("ezekiel", "ez"),
 ("ezekiel", "ezekiel"),
 ("daniel", "dan"),
 ("daniel", "da"),
 ("daniel", "dn"),
 ("daniel", "daniel"),
 ("hosea", "hos"),
 ("hosea", "ho"),
 ("hosea", "hosea"),
 ("joel", "joe"),
 ("joel", "jl"),
 ("joel", "joel"),
 ("amos", "amos"),
 ("amos", "am"),
 ("obadiah", "obad"),
 ("obadiah", "ob"),
 ("obadiah", "obadiah"),
 ("jonah", "jnh"),
 ("jonah", "jon"),
 ("jonah", "jonah"),
 ("micah", "micah"),
 ("micah", "mic"),
 ("micah", "mi"),
 ("nahum", "nah"),
 ("nahum", "na"),
 ("nahum", "nahum"),
 ("habakkuk", "hab"),
 ("habakkuk", "hb"),
 ("habakkuk", "habakkuk"),
 ("zephaniah", "zeph"),
 ("zephaniah", "zep"),
 ("zephaniah", "zp"),
 ("zephaniah", "zephaniah"),
 ("haggai", "hag"),
 ("haggai", "hg"),
 ("haggai", "haggai"),
 ("zechariah", "zech"),
 ("zechariah", "zec"),
 ("zechariah", "zc"),
 ("zechariah", "zechariah"),
 ("malachi", "mal"),
 ("malachi", "ml"),
 ("malachi", "malachi"),

 ("matthew", "matt"),
 ("matthew", "mt"),
 ("matthew", "matthew"),
 ("mark", "mrk"),
 ("mark", "mk"),
 ("mark", "mr"),
 ("mark", "mark"),
 ("luke", "luk"),
 ("luke", "lk"),
 ("luke", "luke"),
 ("john", "john"),
 ("john", "jn"),
 ("john", "jhn"),
 ("acts", "acts"),
 ("acts", "ac"),
 ("romans", "rom"),
 ("romans", "ro"),
 ("romans", "rm"),
 ("romans", "romans"),
 ("1corinthians", "1 cor"),
 ("1corinthians", "1 co"),
 ("1corinthians", "i co"),
 ("1corinthians", "1co"),
 ("1corinthians", "i cor"),
 ("1corinthians", "1cor"),
 ("1corinthians", "i corinthians"),
 ("1corinthians", "1corinthians"),
 ("1corinthians", "1st corinthians"),
 ("1corinthians", "first corinthians"),
 ("1corinthians", "1 corinthians"),
 ("2corinthians", "2 cor"),
 ("2corinthians", "2 co"),
 ("2corinthians", "ii co"),
 ("2corinthians", "2co"),
 ("2corinthians", "ii cor"),
 ("2corinthians", "2cor"),
 ("2corinthians", "ii corinthians"),
 ("2corinthians", "2corinthians"),
 ("2corinthians", "2nd corinthians"),
 ("2corinthians", "second corinthians"),
 ("2corinthians", "2 corinthians"),
 ("galatians", "gal"),
 ("galatians", "ga"),
 ("galatians", "galatians"),
 ("ephesians", "ephes"),
 ("ephesians", "eph"),
 ("ephesians", "ephesians"),
 ("philippians", "phil"),
 ("philippians", "philip"),
 ("philippians", "php"),
 ("philippians", "philippians"),
 ("colossians", "col"),
 ("colossians", "colossians"),
 ("1thessalonians", "1 thess"),
 ("1thessalonians", "1 th"),
 ("1thessalonians", "i th"),
 ("1thessalonians", "1th"),
 ("1thessalonians", "i thes"),
 ("1thessalonians", "1thes"),
 ("1thessalonians", "1 thes"),
 ("1thessalonians", "i thess"),
 ("1thessalonians", "1thess"),
 ("1thessalonians", "i thessalonians"),
 ("1thessalonians", "1thessalonians"),
 ("1thessalonians", "1st thessalonians"),
 ("1thessalonians", "first thessalonians"),
 ("1thessalonians", "1 thessalonians"),
 ("2thessalonians", "2 thess"),
 ("2thessalonians", "2 th"),
 ("2thessalonians", "ii th"),
 ("2thessalonians", "2th"),
 ("2thessalonians", "ii thes"),
 ("2thessalonians", "2thes"),
 ("2thessalonians", "2 thes"),
 ("2thessalonians", "ii thess"),
 ("2thessalonians", "2thess"),
 ("2thessalonians", "ii thessalonians"),
 ("2thessalonians", "2thessalonians"),
 ("2thessalonians", "2nd thessalonians"),
 ("2thessalonians", "second thessalonians"),
 ("2thessalonians", "2 thessalonians"),
 ("1timothy", "1 tim"),
 ("1timothy", "1 ti"),
 ("1timothy", "1 tm"),
 ("1timothy", "i ti"),
 ("1timothy", "1ti"),
 ("1timothy", "i tim"),
 ("1timothy", "1tim"),
 ("1timothy", "i timothy"),
 ("1timothy", "1timothy"),
 ("1timothy", "1st timothy"),
 ("1timothy", "first timothy"),
 ("1timothy", "1 timothy"),
 ("2timothy", "2 tim"),
 ("2timothy", "2 ti"),
 ("2timothy", "2 tm"),
 ("2timothy", "ii ti"),
 ("2timothy", "2ti"),
 ("2timothy", "ii tim"),
 ("2timothy", "2tim"),
 ("2timothy", "ii timothy"),
 ("2timothy", "2timothy"),
 ("2timothy", "2nd timothy"),
 ("2timothy", "second timothy"),
 ("2timothy", "2 timothy"),
 ("titus", "titus"),
 ("titus", "tit"),
 ("titus", "ti"),
 ("philemon", "philem"),
 ("philemon", "phm"),
 ("philemon", "phlm"),
 ("philemon", "philemon"),
 ("hebrews", "hebrews"),
 ("hebrews", "heb"),
 ("james", "1 jacob"),
 ("james", "1 jac"),
 ("james", "1jac"),
 ("james", "james"),
 ("james", "jas"),
 ("james", "jm"),
 ("james", "e jacob"),
 ("james", "ep jacob"),
 ("james", "ejacob"),
 ("james", "epistle of jacob"),
 ("james", "epistle of james"),
 ("1peter", "1 pet"),
 ("1peter", "1 pe"),
 ("1peter", "i pe"),
 ("1peter", "1pe"),
 ("1peter", "i pet"),
 ("1peter", "1pet"),
 ("1peter", "i pt"),
 ("1peter", "1 pt"),
 ("1peter", "1pt"),
 ("1peter", "i peter"),
 ("1peter", "1peter"),
 ("1peter", "1st peter"),
 ("1peter", "first peter"),
 ("1peter", "1 peter"),
 ("2peter", "2 pet"),
 ("2peter", "2 pe"),
 ("2peter", "ii pe"),
 ("2peter", "2pe"),
 ("2peter", "ii pet"),
 ("2peter", "2pet"),
 ("2peter", "ii pt"),
 ("2peter", "2 pt"),
 ("2peter", "2pt"),
 ("2peter", "ii peter"),
 ("2peter", "2peter"),
 ("2peter", "2nd peter"),
 ("2peter", "second peter"),
 ("2peter", "2 peter"),
 ("1john", "1 john"),
 ("1john", "1 jn"),
 ("1john", "i jn"),
 ("1john", "1jn"),
 ("1john", "i jo"),
 ("1john", "1jo"),
 ("1john", "i joh"),
 ("1john", "1joh"),
 ("1john", "i jhn"),
 ("1john", "1 jhn"),
 ("1john", "1jhn"),
 ("1john", "i john"),
 ("1john", "1john"),
 ("1john", "1st john"),
 ("1john", "first john"),
 ("2john", "2 john"),
 ("2john", "2 jn"),
 ("2john", "ii jn"),
 ("2john", "2jn"),
 ("2john", "ii jo"),
 ("2john", "2jo"),
 ("2john", "ii joh"),
 ("2john", "2joh"),
 ("2john", "ii jhn"),
 ("2john", "2 jhn"),
 ("2john", "2jhn"),
 ("2john", "ii john"),
 ("2john", "2john"),
 ("2john", "2nd john"),
 ("2john", "second john"),
 ("3john", "3 john"),
 ("3john", "3 jn"),
 ("3john", "iii jn"),
 ("3john", "3jn"),
 ("3john", "iii jo"),
 ("3john", "3jo"),
 ("3john", "iii joh"),
 ("3john", "3joh"),
 ("3john", "iii jhn"),
 ("3john", "3 jhn"),
 ("3john", "3jhn"),
 ("3john", "iii john"),
 ("3john", "3john"),
 ("3john", "3rd john"),
 ("3john", "third john"),
 ("jude", "jude"),
 ("jude", "jud"),
 ("jude", "jd"),
 ("jude", "judah"),
 ("jude", "judas"),
 ("jude", "epistle of jude"),
 ("revelation", "rev"),
 ("revelation", "rv"),
 ("revelation", "re"),
 ("revelation", "the revelation"),
 ("revelation", "revelation"),

 ("title", "title"),
 ("title", "title page"),
 ("title", "bom title"),
 ("title", "bom title page"),
 ("title", "dedication"),
 ("1nephi", "1st nephi"),
 ("1nephi", "1 ne"),
 ("1nephi", "1 nephi"),
 ("1nephi", "1nephi"),
 ("2nephi", "2nd nephi"),
 ("2nephi", "2 ne"),
 ("2nephi", "2 nephi"),
 ("2nephi", "2nephi"),
 ("jacob", "jacob"),
 ("jacob", "jac"),
 ("enos", "enos"),
 ("enos", "en"),
 ("jarom", "jarom"),
 ("jarom", "jar"),
 ("omni", "omni"),
 ("omni", "om"),
 ("words", "wom"),
 ("words", "w of m"),
 ("words", "words of mormon"),
 ("mosiah", "mosiah"),
 ("mosiah", "mos"),
 ("alma", "alma"),
 ("alma", "al"),
 ("helaman", "hel"),
 ("helaman", "helaman"),
 ("3nephi", "3rd nephi"),
 ("3nephi", "3 ne"),
 ("3nephi", "3 nephi"),
 ("3nephi", "3nephi"),
 ("4nephi", "4th nephi"),
 ("4nephi", "4 ne"),
 ("4nephi", "4 nephi"),
 ("4nephi", "4nephi"),
 ("mormon", "mormon"),
 ("mormon", "morm"),
 ("mormon", "mrm"),
 ("ether", "ether"),
 ("ether", "eth"),
 ("moroni", "moroni"),
 ("moroni", "moro"),
 ("moroni", "mro"),
 ("tow", "tow"),
 ("tow", "testimonies of witnesses"),
 ("tow", "testimony of witnesses"),
 ("tow", "ttw"),
 ("tow", "t3w"),
 ("tow", "ttotw"),
 ("tow", "testimony of three witnesses"),
 ("tow", "testimony of 3 witnesses"),
 ("tow", "the testimony of three witnesses"),
 ("tow", "tew"),
 ("tow", "t8w"),
 ("tow", "ttoew"),
 ("tow", "testimony of eight witnesses"),
 ("tow", "testimony of 8 witnesses"),
 ("tow", "the testimony of eight witnesses"),

 ("epigraph", "epi"),
 ("epigraph", "epigraph"),
 ("section", "t&c"),
 ("section", "section"),
 ("section", "teachings and commandments"),
 ("section", "teachings & commandments"),
 ("section", "tc"),
 ("jshistory", "jsh"),
 ("jshistory", "js-h"),
 ("jshistory", "joseph smith history"),
 ("jshistory", "joseph smith-history"),
 ("jshistory", "jshistory"),
 ("lecture", "lof"),
 ("lecture", "lectures on faith"),
 ("lecture", "lecture"),
 ("abraham", "abr"),
 ("abraham", "abraham"),
 ("toj", "tsj"),
 ("toj", "toj"),
 ("toj", "tosj"),
 ("toj", "testimony of john"),
 ("toj", "testimony of st john"),
 ("toj", "testimony of saint john"),
 ("toj", "test of saint john"),
 ("toj", "test of st john"),
 ("toj", "t of st john"),
 ("toj", "t of john"),
 ("appendix", "appendix"),
 ("appendix", "appx"),
 ("appendix", "perogative"),
 ("appendix", "prerogative"),
 ("appendix", "prophet's prerogative"),

 ("ocforeword", "ocforeword"),
 ("ocforeword", "ocfor"),
 ("ocforeword", "ocf"),
 ("ocforeword", "oc foreword"),
 ("occanonization", "occanonization"),
 ("occanonization", "oc canonization"),
 ("ocpreface", "ocpreface"),
 ("ocpreface", "ocp"),
 ("ocpreface", "oc preface"),
 ("ntpreface", "ntpreface"),
 ("ntpreface", "ntp"),
 ("ntpreface", "nt preface"),
 ("ncforeword", "ncforeword"),
 ("ncforeword", "ncfor"),
 ("ncforeword", "ncf"),
 ("ncforeword", "nc foreword"),
 ("nccanonization", "nccanonization"),
 ("nccanonization", "nc canonization"),
 ("bomintro", "bomintro"),
 ("bomintro", "bomi"),
 ("bomintro", "bom introduction"),
 ("bompreface", "bompreface"),
 ("bompreface", "bom pre"),
 ("bompreface", "bompre"),
 ("bompreface", "bom preface"),
 ("tcforeword", "tcforeword"),
 ("tcforeword", "tc for"),
 ("tcforeword", "tcf"),
 ("tcforeword", "t&c foreword"),
 ("tccanonization", "tccanonization"),
 ("tccanonization", "t&c canonization"),
 ("tcpreface", "tcpreface"),
 ("tcpreface", "tcp"),
 ("tcpreface", "t&c preface"),
 ("tcintro", "tcintro"),
 ("tcintro", "tci"),
 ("tcintro", "t&c introduction"),
 ("glossary", "glossary"),
 ("glossary", "gloss"),
 ("glossary", "glos"),
 ("ocappendix", "oc appendix"),
 ("ocappendix", "oc appx"),
 ("ntappendix", "nt appendix"),
 ("ntappendix", "nt appx"),
 ("bomappendix", "bom appendix"),
 ("bomappendix", "bom appx"),

 ("podcast", "pod"),
 ("podcast", "podcast"),
 ("podcast", "dspod"),
 ("podcast", "dspodcast"),
 ("fyom", "fyom"),
 ("fyom", "40 years"),
 ("fyom", "forty years"),
 ("fyom", "forty years in mormonism"),
COMMIT;
